version: '3.8'

services:
  postgresql:
    image: postgres:15.0
    container_name: postgresql
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: 11asddsa
    ports:
      - "5432:5432"
    volumes:
      - /docker-data/postgresql-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "9001:8080"